spring.application.name=gateway

server.port=5051
eureka.client.serviceUrl.defaultZone=http://localhost:5050/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true